release: ["SVA1_COADD_SPTE",
          "SVA1_COADD_ELGORDO",
          "SVA1_COADD_RXJ",
          "SVA1_COADD_BULLET",
          "SVA1_COADD_COSMOS"]
#release: ["SVA1_COADD_COSMOS"]


astro_rerun_file: "/astro/u/astrodat/data/DES/EXTRA/astrorerun/sva1_astrom_run1.0.1_stats_flagged_sheldon.fit"

min_boxsize: 32
max_boxsize: 256
detband: i
fpack_dims: [10240,1]

magzp_ref: 30.0

bands: ["g","r","i","z"]

comment: |
    These meds files include
        - image id from desdm for SE images
        - coadd_objects_id
        - redone astrometry files, not yet implemented
